  services:
    postgres:
      image: 'postgres:latest'
      ports:
        - '5432:5432'
      environment:
        - DATABASE_URL=jdbc:postgresql://java_db:5432
        - DATABASE_USERNAME=postgres
        - DATABASE_PASSWORD=postgres
      volumes:
        - /data:/var/lib/postgres/data
